/**
 * src/audio/prerecorded.ts
 *
 * Placeholder — this module is auto-generated by scripts/generate-prerecorded.ts.
 * Run `npm run generate-audio` to populate it with actual audio chunks.
 *
 * Each value is an array of base64-encoded ulaw_8000 frames (160 bytes each,
 * 20ms of audio per frame) ready to be placed in Twilio media messages.
 *
 * When empty, the audio cache miss path falls back to live ElevenLabs TTS,
 * so the app works without running the generator (at the cost of per-call
 * TTS latency and spend for these fixed phrases).
 */

/** Role-keyed greeting audio. Each role's audio is rendered in its own voice. */
export const GREETINGS_ULAW: Record<string, string[]> = {};

/** Hold message ("I'm working on that...") keyed by voice ID. */
export const HOLD_ULAW: Record<string, string[]> = {};

/** Generic processing error keyed by voice ID. */
export const ERROR_GENERIC_ULAW: Record<string, string[]> = {};

/** Tool-follow-up error keyed by voice ID. */
export const ERROR_TOOL_ULAW: Record<string, string[]> = {};

/** Text versions for conversation-history bookkeeping. */
export const GREETING_TEXTS: Record<string, string> = {};
export const HOLD_TEXT = "I'm working on that for you right now. I'm still here.";
export const ERROR_GENERIC_TEXT =
  "I'm still here with you. I had a brief technical hiccup on my end, " +
  "but I'm ready whenever you are. Go ahead.";
export const ERROR_TOOL_TEXT =
  "I'm still here. Something went wrong on my end with that last step, " +
  "but don't worry, nothing was lost. What would you like to do next?";
